### ISSUE TITLE
use PasswordSafe to save sensitive connection infos

### ISSUE THREAD

**Issue by tsonglew** [MattMin/a-redis#31]
idea reports the error

```
java.lang.Throwable: Element component@RedisHelper.option.list.ConnectionInfo.option.@name=password probably contains sensitive information (file: FileBasedStorage(file=~/Documents/project-manager/.idea/workspace.xml, fileSpec=$WORKSPACE_FILE$, isBlockSavingTheContent=null))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.configurationStore.JbXmlOutputter.logSensitiveInformationError(JbXmlOutputter.kt:555)
	at com.intellij.configurationStore.JbXmlOutputter.checkIsElementContainsSensitiveInformation(JbXmlOutputter.kt:509)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:246)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:234)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:325)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:264)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:234)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:325)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:264)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:234)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:325)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:264)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:234)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:325)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:264)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:234)
	at com.intellij.configurationStore.XmlDataWriter.write$intellij_platform_configurationStore_impl(XmlElementStorage.kt:273)
	at com.intellij.configurationStore.StringDataWriter.write(XmlElementStorage.kt:431)
	at com.intellij.configurationStore.DataWriter$DefaultImpls.write$default(XmlElementStorage.kt:411)
	at com.intellij.configurationStore.FileBasedStorageKt.doWrite(FileBasedStorage.kt:351)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:303)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:117)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession$SaveExecutor.save(XmlElementStorage.kt:165)
	at com.intellij.configurationStore.SaveExecutorKt.executeSave(SaveExecutor.kt:92)
	at com.intellij.configurationStore.SaveExecutorKt.saveSessions(SaveExecutor.kt:86)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1$lambda$1.compute(actions.kt:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$13(ApplicationImpl.java:1032)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1032)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1.invokeSuspend(ComponentStoreImpl.kt:723)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

it's recommended to use PasswordSafe to persist sensitive data in [IntelliJ Platform Plugin SDK](https://plugins.jetbrains.com/docs/intellij/persisting-sensitive-data.html?from=jetbrains.org)

**Comment by MattMin** [comment]
Updated in the latest version(beta-0.9.0)
